import time, requests
from fastapi import FastAPI
from fastapi.responses import HTMLResponse
app=FastAPI(title='Park LIVE')
PARKS={'LAND':'3cc919f1-d16d-43e0-8c3f-1dd269bd1a42','SEA':'67b290d5-3478-4f23-b601-2f8fb71ba803'}
cache={}
def fetch(url):
    h=cache.get(url); now=time.time()
    if h and now-h[0]<300:return h[1]
    r=requests.get(url,timeout=15,headers={'User-Agent':'Park-LIVE/1.0'});r.raise_for_status();d=r.json();cache[url]=(now,d);return d
@app.get('/api/{park}/live')
def live(park:str):
    try:
        d=fetch('https://api.themeparks.wiki/v1/entity/'+PARKS.get(park.upper(),PARKS['LAND'])+'/live')
        src=d if isinstance(d,list) else d.get('liveData',d.get('data',[])); out=[]
        for x in src:
            q=x.get('queue') or {}; s=q.get('STANDBY') or q.get('standby') or {}
            out.append({'id':x.get('id'),'name':x.get('name','名称不明'),'type':x.get('entityType','ATTRACTION'),'status':x.get('status','UNKNOWN'),'wait':s.get('waitTime'),'updated':x.get('lastUpdated')})
        return {'ok':True,'items':out}
    except Exception as e:return {'ok':False,'items':[],'error':str(e)}
HTML="""<!doctype html><html lang=ja><head><meta charset=utf-8><meta name=viewport content='width=device-width,initial-scale=1,viewport-fit=cover'><title>Park LIVE</title><style>
*{box-sizing:border-box}body{margin:0;background:#0b1020;color:#f8fafc;font-family:system-ui}.w{max-width:720px;margin:auto;padding:16px 16px 90px}.top{display:flex;justify-content:space-between;align-items:center}.brand{font-size:26px;font-weight:900}.sub,.meta{font-size:12px;color:#94a3b8}.seg{background:#172033;padding:4px;border-radius:14px}.seg button,.chip{border:0;border-radius:11px;padding:9px 12px;background:transparent;color:#94a3b8;font-weight:800}.seg .on,.chip.on{background:#fff;color:#111827}.hero{margin:16px 0;padding:18px;border-radius:22px;background:linear-gradient(135deg,#172554,#312e81)}.hero h2{margin:0 0 5px}.chips{display:flex;gap:8px;overflow:auto;margin:12px 0}.chip{border:1px solid #334155;white-space:nowrap}.card{background:#111827;border:1px solid #263248;border-radius:18px;padding:14px;margin:10px 0;display:grid;grid-template-columns:1fr auto}.name{font-weight:800}.wait{font-size:30px;font-weight:900;text-align:right}.fav{border:0;background:none;font-size:22px}.state{text-align:center;color:#94a3b8;padding:30px}.bar{position:fixed;bottom:0;left:0;right:0;background:#0b1020ee;border-top:1px solid #263248;display:flex;justify-content:center;padding:8px}.bar button{width:min(25%,180px);border:0;background:none;color:#94a3b8;padding:8px;font-weight:800}.bar .on{color:white}.foot{text-align:center;color:#64748b;font-size:11px;margin:25px}a{color:#93c5fd}</style></head><body><div class=w><div class=top><div><div class=brand>Park LIVE</div><div class=sub id=stamp>今のパークを、ひと目で。</div></div><div class=seg><button id=LAND class=on>LAND</button><button id=SEA>SEA</button></div></div><div class=hero><h2 id=title>PLAY LIVE</h2><div class=sub>待ち時間を一覧で比較。購入・予約は公式アプリで。</div><div class=meta id=sum>取得中…</div></div><div class=chips><button class='chip on' data-f=all>すべて</button><button class=chip data-f=30>30分以下</button><button class=chip data-f=fav>♥ お気に入り</button></div><div id=list class=state>読み込み中…</div><div class=foot>非公式アプリです。<a href='https://www.themeparks.wiki/' target=_blank>Powered by ThemeParks.wiki</a></div></div><div class=bar><button class=on data-tab=PLAY>▶<br>PLAY</button><button data-tab=EAT>●<br>EAT</button><button data-tab=SHOP>◆<br>SHOP</button><button data-tab=HOME>⌂<br>HOME</button></div><script>
let park='LAND',tab='PLAY',filter='all',items=[],favs=new Set(JSON.parse(localStorage.getItem('plf')||'[]'));const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];function ok(x){let t=(x.type||'').toUpperCase();return tab==='HOME'||t===(tab==='PLAY'?'ATTRACTION':tab==='EAT'?'RESTAURANT':'SHOP')}function esc(s){let d=document.createElement('div');d.textContent=s;return d.innerHTML}function render(){let a=items.filter(ok);if(tab==='HOME')a=a.filter(x=>favs.has(x.id));if(filter==='30')a=a.filter(x=>x.wait!=null&&x.wait<=30);if(filter==='fav')a=a.filter(x=>favs.has(x.id));a.sort((x,y)=>(x.wait??9999)-(y.wait??9999));$('#title').textContent=tab==='HOME'?'NOW / FAVORITES':tab+' LIVE';$('#sum').textContent=park+'・'+a.length+'件 / 5分キャッシュ';if(!a.length){$('#list').className='state';$('#list').textContent=tab==='SHOP'?'ショップのライブ情報は取得元にありません。推測表示はしません。':'表示できる情報がありません。';return}$('#list').className='';$('#list').innerHTML=a.map(x=>`<div class=card><div><div class=name><button class=fav data-id='${x.id}'>${favs.has(x.id)?'♥':'♡'}</button> ${esc(x.name)}</div><div class=meta>${esc(x.status||'UNKNOWN')} ・ ${x.updated?new Date(x.updated).toLocaleTimeString('ja-JP',{hour:'2-digit',minute:'2-digit'}):'時刻不明'}</div></div><div><div class=wait>${x.wait??'–'}</div><div class=meta>${x.wait==null?'待ち時間不明':'分'}</div></div></div>`).join('');$$('.fav').forEach(b=>b.onclick=()=>{favs.has(b.dataset.id)?favs.delete(b.dataset.id):favs.add(b.dataset.id);localStorage.setItem('plf',JSON.stringify([...favs]));render()})}async function load(){$('#list').className='state';$('#list').textContent='読み込み中…';try{let d=await(await fetch('/api/'+park+'/live')).json();items=d.items||[];$('#stamp').textContent=d.ok?'更新 '+new Date().toLocaleTimeString('ja-JP',{hour:'2-digit',minute:'2-digit'}):'取得エラー';render()}catch(e){$('#list').textContent='データを取得できませんでした。'}}$$('.seg button').forEach(b=>b.onclick=()=>{park=b.id;$$('.seg button').forEach(x=>x.classList.toggle('on',x.id===park));load()});$$('.chip').forEach(b=>b.onclick=()=>{filter=b.dataset.f;$$('.chip').forEach(x=>x.classList.toggle('on',x===b));render()});$$('.bar button').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;$$('.bar button').forEach(x=>x.classList.toggle('on',x===b));render()});load();
</script></body></html>"""
@app.get('/',response_class=HTMLResponse)
def home():return HTML
